version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mockstalk-mysql
    environment:
      MYSQL_DATABASE: mockstalk
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mockstalk-net

  redis:
    image: redis:7
    container_name: mockstalk-redis
    ports:
      - "6379:6379"
    networks:
      - mockstalk-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mockstalk-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - mockstalk-net

  app:
    image: mockstalk-app:latest
    container_name: mockstalk-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      HANTU_APPKEY: ${HANTU_APPKEY}
      HANTU_APPSECRET: ${HANTU_APPSECRET}
    depends_on:
      - mysql
      - redis
      - rabbitmq
    networks:
      - mockstalk-net

volumes:
  mysql-data:

networks:
  mockstalk-net: